### ISSUE TITLE
おめでとうございます！

### ISSUE THREAD

**Issue by k-taro56** [k-taro56/for-chat#1]
@clcl777
最優秀賞おめでとうございます㊗️🎉🎉🎊🎊🍾

**Comment by clcl777** [comment]
@k-taro56 ありがとう！！
こんなgithubの使い方があったとはw

**Comment by k-taro56** [comment]
@clcl777
GitHub しか知らなかったのでね〜
届いてよかったです！GitHub も SNS かも
これからもがんばってください👍

**Comment by clcl777** [comment]
@k-taro56 
ありがとうございます！！
k-taro56くんもがんばって！！！

**Comment by clcl777** [comment]
今更ながら、しっかりとtwitterアカウント作ったよ
https://twitter.com/tra_earth

**Comment by k-taro56** [comment]
じゃあこのイシューは用済みですね
クローズしときますね
